export const guest_routers = [
  {
    title: 'Tin nhắn',
    icon: '/assets/images/guest/ic_menu_chat.svg',
    visible: true,
    key: 'chat',
    path: '/home/guest/chat',
  },
  {
    title: 'Hồ sơ',
    icon: '/assets/images/guest/ic_menu_profile.svg',
    visible: true,
    key: 'profile',
    path: '/home/guest/profile',
  },
  {
    title: 'Tài liệu',
    icon: '/assets/images/guest/ic_menu_folder.svg',
    visible: true,
    key: 'document',
    path: '/home/guest/document',
  },
  {
    title: 'Phê duyệt',
    icon: '/assets/images/guest/ic_menu_approval.svg',
    visible: true,
    key: 'message',
    path: '/home/guest/approval',
  },
  {
    title: 'Đặt xe',
    icon: '/assets/images/guest/ic_menu_booking_car.svg',
    visible: true,
    key: 'bookingCar',
    menu: 'bookingCar',
    path: '/home/guest/extra/booking-car',
  },
  {
    title: 'Đặt phòng',
    icon: '/assets/images/guest/ic_menu_booking_room.svg',
    visible: true,
    key: 'bookingRoom',
    menu: 'bookingRoom',
    path: '/home/guest/extra/booking-room',
  },
  {
    title: 'Bảng lương',
    icon: '/assets/images/guest/ic_menu_payslip.svg',
    visible: true,
    key: 'payslip',
    menu: 'payslip',
    path: '/home/guest/extra/payslip',
  },
  {
    title: 'Công việc',
    icon: '/assets/images/guest/guess_task.svg',
    visible: true,
    key: 'guestTask',
    menu: 'guestTask',
    path: '/home/guest/task',
  },
]
